#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

/**
 * Script to generate CommonJS versions of ESM modules
 * This is used as part of the build process to support both ESM and CommonJS imports
 */

// Get the directory where this script is executed from
const currentDir = process.cwd();
const distDir = path.join(currentDir, 'dist');

// Check if dist directory exists
if (!fs.existsSync(distDir)) {
    console.error(`Error: dist directory does not exist at ${distDir}`);
    process.exit(1);
}

// List of files to create CJS versions for
const filesToProcess = [
    'index.js',
    'public-api.js'
];

console.log(`Creating CommonJS versions in ${distDir}...`);

// Process each file
for (const file of filesToProcess) {
    const sourceFile = path.join(distDir, file);
    const targetFile = path.join(distDir, file.replace('.js', '.cjs'));

    if (fs.existsSync(sourceFile)) {
        const cjsContent = `'use strict';

// This is an auto-generated CommonJS wrapper for the ESM module
// Generated by postbuild-dual.js
module.exports = require('./${path.basename(file)}');
`;

        fs.writeFileSync(targetFile, cjsContent);
        console.log(`Created ${targetFile}`);
    } else {
        console.warn(`Warning: Source file ${sourceFile} not found, skipping CJS generation`);
    }
}

console.log('CommonJS conversion complete!'); 